# Homebrew formula for Anderson
# Auto-generated by release workflow

class Anderson < Formula
  desc "CLI for interacting with LetsMOD agentic services"
  homepage "https://github.com/letsmod/anderson"
  license "Proprietary"
  version "0.3.0"

  on_macos do
    on_arm do
      url "https://static.letsmod.com/releases/anderson/0.3.0/anderson_0.3.0_darwin_arm64.tar.gz"
      sha256 "ed97a1bc645a0d2e0ae81ba9d09f3573c3a3a7c5c3c3142cb5ce2c64f19b3a76"
    end
    on_intel do
      url "https://static.letsmod.com/releases/anderson/0.3.0/anderson_0.3.0_darwin_amd64.tar.gz"
      sha256 "9d4124ca839863884f64c559a120dd7c0efeab483caf272b8890dad5431854a9"
    end
  end

  on_linux do
    on_arm do
      url "https://static.letsmod.com/releases/anderson/0.3.0/anderson_0.3.0_linux_arm64.tar.gz"
      sha256 "cb4642031d4bf8179817da9d013ba89c6f3c315035950153f2c1780bf5a53805"
    end
    on_intel do
      url "https://static.letsmod.com/releases/anderson/0.3.0/anderson_0.3.0_linux_amd64.tar.gz"
      sha256 "edfe7971e3dd373e8bb4afca2a14851bfa72e875f9df426906fa4963ad440647"
    end
  end

  def install
    bin.install "anderson"
  end

  test do
    system "#{bin}/anderson", "--help"
  end
end
