# Homebrew formula for Anderson
# Auto-generated by release workflow

class Anderson < Formula
  desc "CLI for interacting with LetsMOD agentic services"
  homepage "https://github.com/letsmod/anderson"
  license "Proprietary"
  version "0.3.6"

  on_macos do
    on_arm do
      url "https://static.letsmod.com/releases/anderson/0.3.6/anderson_0.3.6_darwin_arm64.tar.gz"
      sha256 "e9aa51a0f25c0fdf50fc813d6461d53e184b2cff90dc3b49202f23029cd53fb3"
    end
    on_intel do
      url "https://static.letsmod.com/releases/anderson/0.3.6/anderson_0.3.6_darwin_amd64.tar.gz"
      sha256 "42eae81d179031a8a967822300f3018d1faa2cb3d2f48255d49178bd018ed2fb"
    end
  end

  on_linux do
    on_arm do
      url "https://static.letsmod.com/releases/anderson/0.3.6/anderson_0.3.6_linux_arm64.tar.gz"
      sha256 "a372358e0a69101c641a9ecdcbba4ae88a93143da8757be741955eddeb9615ea"
    end
    on_intel do
      url "https://static.letsmod.com/releases/anderson/0.3.6/anderson_0.3.6_linux_amd64.tar.gz"
      sha256 "e8fb3ed47c335fe0db4b1dbf769669de1f28415bdc1bb832098e4b3e21311fd8"
    end
  end

  def install
    bin.install "anderson"
  end

  test do
    system "#{bin}/anderson", "--help"
  end
end
