# Homebrew formula for Dropbox
# Auto-generated by release workflow

class Dropbox < Formula
  desc "Syncs work orders and files between S3 and local storage"
  homepage "https://github.com/letsmod/dropbox"
  license "Proprietary"
  version "0.1.0"

  on_macos do
    on_arm do
      url "https://static.letsmod.com/releases/dropbox/0.1.0/dropbox_0.1.0_darwin_arm64.tar.gz"
      sha256 "68be49abf0520487491fe229451053c88b01f7101074c83e0b744dfb098e7b3d"
    end
    on_intel do
      url "https://static.letsmod.com/releases/dropbox/0.1.0/dropbox_0.1.0_darwin_amd64.tar.gz"
      sha256 "db3ffb4512fb7da51ddef21bf0c05aa05052d5cf88a48e9cb1f27bd4159819bd"
    end
  end

  on_linux do
    on_arm do
      url "https://static.letsmod.com/releases/dropbox/0.1.0/dropbox_0.1.0_linux_arm64.tar.gz"
      sha256 "38d168fa186f630e6e0ef645b0cc1eaaf5d75193943186299bbf630fdba1cc1c"
    end
    on_intel do
      url "https://static.letsmod.com/releases/dropbox/0.1.0/dropbox_0.1.0_linux_amd64.tar.gz"
      sha256 "f9951793fbc8c06abd30b1b97a3b3a4c63a2e978c1f999004870e1da42c9b233"
    end
  end

  def install
    bin.install "dropbox"
  end

  test do
    system "#{bin}/dropbox", "--help"
  end
end
