# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Trinity < Formula
  desc "CLI for interacting with LetsMOD agentic services"
  homepage "https://github.com/letsmod/trinity"
  version "0.1.2"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://static.letsmod.com/releases/trinity/0.1.2/trinity_0.1.2_darwin_amd64.tar.gz"
      sha256 "15b698b0c04c1aa9be907320cf3ff43bde818888c0aa4f0f3441e9ae4638fe97"

      def install
        bin.install "trinity"
      end
    end
    if Hardware::CPU.arm?
      url "https://static.letsmod.com/releases/trinity/0.1.2/trinity_0.1.2_darwin_arm64.tar.gz"
      sha256 "d7c9e9e12ea1ae1be7647d3d8c126531ef0b8f04728a97006004a86124b2d3c8"

      def install
        bin.install "trinity"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://static.letsmod.com/releases/trinity/0.1.2/trinity_0.1.2_linux_amd64.tar.gz"
      sha256 "56d8796a3b6c2e23fd85e88c2beb352e442c67bd7ee306b7fac42a8472279faa"
      def install
        bin.install "trinity"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://static.letsmod.com/releases/trinity/0.1.2/trinity_0.1.2_linux_arm64.tar.gz"
      sha256 "7b020124d87996e1163d283e1256a8d746e661e5690e7388ce7fd18c45c301f6"
      def install
        bin.install "trinity"
      end
    end
  end
end
