# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Trinity < Formula
  desc "CLI for interacting with LetsMOD agentic services"
  homepage "https://github.com/letsmod/trinity"
  version "0.1.1"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/letsmod/trinity/releases/download/v0.1.1/trinity_0.1.1_darwin_amd64.tar.gz"
      sha256 "6fd933425e59b047ac56333d219fe49a1ba130f61c2e6144f2d2e59e97150fe6"

      def install
        bin.install "trinity"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/letsmod/trinity/releases/download/v0.1.1/trinity_0.1.1_darwin_arm64.tar.gz"
      sha256 "52f801f9eb9aef12648186cec46a761533f4e403679a0313d4ac6abce046a9d8"

      def install
        bin.install "trinity"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/letsmod/trinity/releases/download/v0.1.1/trinity_0.1.1_linux_amd64.tar.gz"
      sha256 "71da92f9a9629c3eaf6757182710d2d6c389b05c7673e75e7029d353c1157d76"
      def install
        bin.install "trinity"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/letsmod/trinity/releases/download/v0.1.1/trinity_0.1.1_linux_arm64.tar.gz"
      sha256 "e1c3eef13a43b46ac4b0b09ee4d36fddec3a003b7476dd65d2a9212881b0be03"
      def install
        bin.install "trinity"
      end
    end
  end
end
